### ISSUE TITLE
Error when parsing changelog with version links

### ISSUE THREAD

**Issue by michaelborn** [Gustry/changelog-release#8]
When parsing a changelog in this format:

```md
## [Unreleased]

## [5.4.29.25] - 2023-05-23

## Changed

- Switched to Maven for a faster, more stable build process
- Improved entity event listeners for a much speedier ORM startup (8924b58a9058d296e2a783ccfabbf90e26dc9c1b)
- New and Improved logo for Lucee admin visibility (10bdf56a7a78f0221ab1a6e66a5512a92819e5b7)

## Fixed

- Entity has no state when listener method (`onPreInsert`, for example) is fired (014814263b5d31b8bac4c17479c2ca731ceb4e7c, [OOE-1](https://ortussolutions.atlassian.net/browse/OOE-1))

[Unreleased]: https://github.com/Ortus-Solutions/extension-hibernate/compare/v5.4.29.25...HEAD

[5.4.29.25]: https://github.com/Ortus-Solutions/extension-hibernate/compare/80d6ad971c06a955ec0e308f2c8149ee7119654d...v5.4.29.25
```

I get an error that `raw` doesn't exist on the version variable:

```sh
Traceback (most recent call last):
  File "/main.py", line 165, in <module>
    main()
  File "/main.py", line 135, in main
    info = add_emoji(info, end=end_of_line)
  File "/main.py", line 64, in add_emoji
    content = version_changelog['raw'].split('\n')
KeyError: 'raw'
```

Is this because the `[5.4.29.25]` string is being picked up twice? Note that this is following the [Keep a Changelog standard](https://keepachangelog.com/en/1.1.0/), and is the default output from [`thomaseizinger/keep-a-changelog-new-release@1.3.0`](https://github.com/thomaseizinger/keep-a-changelog-new-release).

**Comment by Gustry** [comment]
Thanks for the ticket.

This repository is only using an external Python library for parsing changelog and wrapping it into a docker image for the GH Action.

Your issue must be raised in the Python tool used to parse your changelog I think : https://github.com/Colin-b/keepachangelog

But a quick look, it seems your example is provided in the README.md file : https://github.com/Colin-b/keepachangelog#convert-changelog-to-dict
